services:
  registry:
    image: distribution/distribution:3.0.0
    environment:
      KEY: value
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./distribution.yml:/etc/distribution/config.yml
